config/routes.rb
Store::Application.routes.draw do
  
  devise_for :admins
  
  resources :baskets do
    resources :line_items
  end

  resources :categories
  
  resources :items do
    collection do
      post 'search'
    end
    resources :item_options
  end
  
  resources :pages
  
  resources :payment_notifications, :only => [:create]
  
  root :to => 'items#recent'
  
end

app/views/shared/_added_to_basket.html.haml
= "Item added to basket. #{link_to 'Go to basket', basket_url(current_basket)} &raquo;".html_safe

app/views/shared/_basket.html.haml
%div#shopping-basket
	%h2
		= link_to t(:basket_title, :scope => 'views.basket'), basket_path(basket)
	%ul
		- if basket.line_items.count.zero?
			%li.empty
				You have no items in your basket.
		- else
			- for li in basket.line_items
				%li
					%div
						%a{:href => li.item.image.url, :title => li.item.name, :rel => 'cart-gallery'}
							%img{:src => li.item.image.url(:icon), :alt => li.item.name}
					%div
						- if li.item.parent
							= link_to li.item.parent.name, li.item
						- else
							=link_to li.item.name, li.item
						%span
							x#{li.quantity}
							=ntc li.item.price
			%li.total
				Subtotal:
				=ntc basket.subtotal

app/views/shared/_items.html.haml
%div
	%a{:href => item_path(item)}
		%img{:src => item.image(:thumb)}
		%p= item.name
	- if admin_signed_in?
		%span.small
			= link_to 'Edit', edit_item_path(item)
			|
			= link_to 'Destroy', item_path(item), :confirm => "Delete item '#{item.name}'?", :method => :delete

app/views/shared/_navigation.html.haml
- clss = ''

= render :partial => 'shared/page_navigation', :collection => nav_collection, :as => :page

- unless basket.line_items.count.zero?
	%li
		- clss = 'current' if controller.controller_name == 'baskets'
		= link_to 'Basket', basket_path(basket), :class => clss
		

- if admin_signed_in?
	%li
		=link_to '[Pages]', pages_path
/
	%li.search
		= form_tag search_items_path, :method => 'post' do
			= text_field_tag :search, params[:search]

app/views/shared/_page.html.haml
- page = Page.find_by_links_to(request.path) if page.nil?

- unless page.nil?
	= title page.name
	
	:markdown
		#{page.content}
		
	- if page.sidebar
		- content_for :sidebar do
			:markdown
				#{page.sidebar}

app/views/shared/_page_navigation.html.haml
-# clss = ''
- unless page.published == false
	%li
		- unless page.links_to?
			- clss = 'current' if request.path == "/pages/#{page.permalink}"
			= link_to h(page.name), { :controller => '/pages', :action => 'show', :id => page.permalink }, :class => clss
		- else
			- clss = 'current' if request.path == page.links_to
			= link_to h(page.name), page.links_to, :class => clss

		- unless page.children.empty?
			%ul
				= render :partial => 'shared/menubar', :collection => page.children, :as => :page

app/views/shared/_sidebar.html.haml
- if content_for? :sidebar
	= yield :sidebar

- unless controller.controller_name == 'baskets'
	= render 'shared/basket', :basket => current_basket
- else
	%h1
		Help
	%p
		Aliquam erat volutpat. Mauris vel neque sit amet nunc gravida congue sed sit amet purus.
	%p
		Vestibulum mollis mauris enim. Morbi euismod magna ac lorem rutrum elementum. Donec viverra auctor lobortis.

	%img{:src => '/images/paypal.gif', :alt => 'This site uses PayPal.'}