config/routes.rb
Store::Application.routes.draw do
  
  devise_for :admins
  
  resources :baskets do
    resources :line_items
  end

  resources :categories
  
  resources :items do
    collection do
      post 'search'
    end
    resources :item_options
  end
  
  resources :pages
  
  resources :payment_notifications, :only => [:create]
  
  root :to => 'items#recent'
  
end

app/views/pages/_form.html.haml
= form_for page, :html => {:class => 'admin'} do |f|
	-if page.errors.any?
		#error_explanation
			%h2= "#{pluralize(page.errors.count, "error")} prohibited this page from being saved:"
			%ul
				- page.errors.full_messages.each do |msg|
					%li= msg

	.field
		= f.label :name
		= f.text_field :name
	.field
		= f.label :content
		= f.text_area :content
	.field
		= f.label :sidebar
		= f.text_area :sidebar
	.field
		= f.label :permalink
		= f.text_field :permalink
	.field
		= f.label :links_to
		= f.text_field :links_to
	.field
		= f.label :order
		= f.text_field :order
	.field
		= f.label :published
		= f.check_box :published
	.actions
		= f.submit 'Save'

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form', :page => @page

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/index.html.haml
%h1 Listing pages

%table
  %tr
    %th Name
    %th Content
    %th Permalink
    %th Links to
    %th Order
    %th Parent
    %th{:colspan => 3} Actions

  - @pages.each do |page|
    %tr
      %td= page.name
      %td= truncate page.content
      %td= page.permalink
      %td= page.links_to
      %td= page.order
      %td= page.parent_id
      %td= link_to 'Show', page
      %td= link_to 'Edit', edit_page_path(page)
      %td= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New page

= render 'form', :page => @page

= link_to 'Back', pages_path

app/views/pages/show.html.haml
= render :partial => 'shared/page'

- if admin_signed_in?
	.hilight
		= link_to 'Edit', edit_page_path(@page)
		|
		= link_to 'Back', pages_path