config/routes.rb
Store::Application.routes.draw do
  
  devise_for :admins
  
  resources :baskets do
    resources :line_items
  end

  resources :categories
  
  resources :items do
    collection do
      post 'search'
    end
    resources :item_options
  end
  
  resources :pages
  
  resources :payment_notifications, :only => [:create]
  
  root :to => 'items#recent'
  
end

app/models/item.rb
# coding: utf-8
class Item < ActiveRecord::Base
  has_many :line_items
  has_many :options, :class_name => 'Item', :foreign_key => 'item_id'
  belongs_to :super, :class_name => 'Item'
  has_and_belongs_to_many :categories
  
  # allow image deletion on forms
  attr_accessor :delete_image
  before_save :image_deletion
  
  # if some one has an item in their basket, don't destroy it
  before_destroy :ensure_not_referenced_by_line_item
  
  # has children
  acts_as_tree
  
  # search
  index do
    name
    description
  end
  
  # validation
  validates_presence_of :name, :price, :stock, :description
  validates_uniqueness_of :name
  validates_numericality_of :price
  validates_numericality_of :stock, :integer => true
  
  # scope to find only 'top level' items, i.e. no options
  scope :top_level, lambda {
    where(:parent_id => nil)
  }
  
  # recent items
  scope :recent, lambda { |number|
    order('id desc').limit(number)
  }
  
  # paperclip
  has_attached_file :image,
                    :styles => { :thumb => '128x128#', :option => '32x32#', :icon => '16x16#' },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :s3_host_alias => 's3.alexpearce.me',
                    :url => ":s3_alias_url",
                    :path => "/store/:class/:attachment/:id/:normalized_basename_:style.:extension",
                    :default_url => "/images/items/missing_:style.png"
                    
  
  def create_new_option
    self.children.new(
      :price => self.price,
      :stock => self.stock,
      :postage => self.postage
    )
  end
  
  # generate the image path
  def image_path
    '/images/' + self.image
  end
  
  # return a string showing the parent item and the option name in parens
  def self_with_parent
    if self.parent
      "#{self.parent.name} (#{self.name})"
    else
      self.name
    end
  end
  
  # return string for the dropdown on the item page
  def option_select
    ret = "#{self.name} - £#{sprintf("%.2f", self.price)}"
    ret.concat ' (Sold Out)' if self.stock == 0
    return ret
  end
  
  private
  
    def image_deletion
      self.image = nil if self.delete_image == '1'
    end
  
    def ensure_not_referenced_by_line_item
      if line_items.count.zero?
        true
      else
        errors[:base] << 'Line Items present.'
        false
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_filter :authenticate_admin!, :except => [:index, :show, :search, :recent]
  
  respond_to :html
  
  def recent
    @items = Item.top_level.recent(6)
    
    respond_with @items
  end
  
  def index
    @items = Item.top_level
    
    respond_with @items
  end
  
  def search
    @items = Item.search(params[:search])
    @items.count == 0 ?
      redirect_to(items_path, :notice => 'No items matched your search.') : render(:search)
  end

  def show
    @item = Item.find(params[:id], :include => :categories)
    @line_item = LineItem.new(:item_id => @item.id)
    @item.parent ?
      redirect_to(item_path(@item.parent), :flash => flash) : respond_with(@item)
  end

  def new
    if params[:parent_id]
      @parent = Item.find(params[:parent_id])
      @item = @parent.create_new_option
    else
      @item = Item.new
    end

    respond_with @item
  end

  def edit
    @item = Item.find(params[:id])
    @children = @item.children
        
    respond_with @item
  end

  def create
    @item = Item.new(params[:item])
    @item.categories.build(params[:item][:category]) if params[:item][:category]
    @item.save ?
      flash[:notice] = 'New item successfully created.' :  flash[:notice] = 'New item not successfully created.'
    
    respond_with @item
  end

  def update
    @item = Item.find(params[:id])
    params[:item][:category_ids] ||= []
    if @item.update_attributes(params[:item])
      flash[:notice] = 'Item successfully updated.'
    else
      @children = @item.children
      flash[:error] = 'Item not successfully updated.'
    end
    
    respond_with @item
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy ?
      flash[:notice] = 'Item successfully destroyed.' : flash[:alert] = 'Destroy unsuccessful. Item may be referenced by line items.'
    
    respond_with @item
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def options_select(name, price, stock)
    if stock == 0
      "#{name} - #{sprintf("%.2f", price)} (Sold Out)"
    else
      "#{name} - #{sprintf("%.2f", price)}"
    end
  end
end

app/views/items/_form.html.haml
= form_for item, :html => { :multipart => true, :class => 'admin' } do |f|
	-if item.errors.any?
		#error_explanation
			%h2= "#{pluralize(item.errors.count, "error")} prohibited this item from being saved:"
			%ul
				- item.errors.full_messages.each do |msg|
					%li= msg
				
	= f.hidden_field :parent_id
	
	.field
		= f.label :name
		= f.text_field :name
	.field
		= f.label :price
		= f.text_field :price
	.field
		= f.label :stock
		= f.text_field :stock
	.field
		= f.label :postage
		= f.text_field :postage
	.field
		= f.label :description
		= f.text_area :description
	.field.media
		.meta
			= f.label :category_ids, 'Categories'
		.body
			- Category.all.each_with_index do |c, idx|
				.field
					= label_tag "item_category_ids_#{idx}", c.name
					= check_box_tag 'item[category_ids][]', c.id, item.categories.include?(c), :id => "item_category_ids_#{idx}"
	.field
		= f.label :image
		= f.file_field :image
	.field
		= f.label :delete_image, 'Delete Image?'
		= f.check_box :delete_image
	.actions
		= f.submit 'Save'

app/views/items/_search.html.haml
=title 'Search Results'

%p= "Search results for #{params[:search]}"

= render :partial => 'layouts/items', :locals => {:items => @items}

app/views/items/edit.html.haml
= title "Editing Option '#{@item.name}'" if @item.parent
= title "Editing Item '#{@item.name}'" if @item.parent.nil?

= render :partial => 'form', :locals => { :item => @item }

- unless @children.empty?
	%h2 Options
	- @children.each do |c|
		%a{:href => c.image.url, :title => c.name, :rel => 'option'}
			%img{:src => c.image.url(:option), :class => 'thumbShadow', :alt => c.name}
		%p
			= link_to 'Edit', edit_item_path(c)
			|
			= link_to 'Destroy', item_path(c), :confirm => "Delete option '#{c.name}' for item '#{@item.name}'?", :method => :delete
	
%p
	= link_to "Back to #{@item.parent.name}", edit_item_path(@item.parent) if @item.parent

app/views/items/index.html.haml
= render 'shared/page', :page => @page

.items-container
	= render :partial => 'shared/items', :collection => @items, :as => :item

- if admin_signed_in?
	%p
		= link_to 'New Item', new_item_path

app/views/items/new.html.haml
- if @parent.nil?
	= title 'Create New Item'
- else
	= title "Create Option for #{@parent.name}"

= render 'form', :item => @item

= link_to 'Back', items_path

app/views/items/recent.html.haml
= render 'shared/page'

.items-container
	= render :partial => 'shared/items', :collection => @items, :as => :item

app/views/items/search.html.haml
=title 'Search Results'

%p
	Search results for 
	%strong.highlight="#{params[:search]}"

.items-container
	= render :partial => 'shared/items', :collection => @items, :as => :item

app/views/items/show.html.haml
= title @item.name
		
.media
	.meta
		%a{:href => @item.image.url, :title => @item.name, :rel => 'items-gallery'}
			%img{:src => @item.image.url(:thumb), :alt => @item.name, :class => 'item-image'}
		- unless @item.children.empty?
			%h2 Options
			- @item.children.each do |c|
				%a{:href => c.image.url, :title => "#{@item.name} - #{c.name}", :rel => 'items-gallery'}
					%img{:src => c.image.url(:option), :alt => c.name}
					

	.body
		:markdown
			#{@item.description}
		
		- unless @item.categories.count == 0
			.categories
				%h3= link_to 'Categories', categories_path, :class => 'title'
				%ul
					- @item.categories.sort_by(&:name).each do |c|
						%li= link_to c.name, category_path(c), :class => 'tag'
		
		.item-meta
			- if admin_signed_in?
				= link_to 'Add Option', new_item_path(:parent_id => @item)
				|
				= link_to 'Edit', edit_item_path(@item)
				|
				= link_to 'Destroy', item_path(@item), :confirm => "Delete item '#{@item.name}'?", :method => :delete

			%span.price= ntc @item.price
		
		.add-to-basket
			= form_for [current_basket, @line_item], :html => {:class => 'right'} do |f|
				.field
					- if @item.children.empty?
						= f.hidden_field :item_id
					- else
						= f.collection_select :item_id, @item.children, :id, :option_select, { :disabled => lambda{ |op| op.stock == 0 }, :include_blank => 'Choose an option'}
				.actions
					= f.submit 'Add to Basket' if @item.stock > 0
					= f.submit 'Sold Out', :disabled => 'disabled' if @item.stock == 0