config/routes.rb
Store::Application.routes.draw do
  
  devise_for :admins
  
  resources :baskets do
    resources :line_items
  end

  resources :categories
  
  resources :items do
    collection do
      post 'search'
    end
    resources :item_options
  end
  
  resources :pages
  
  resources :payment_notifications, :only => [:create]
  
  root :to => 'items#recent'
  
end

app/views/layouts/_navigation.html.haml
- clss = ''

= render :partial => 'layouts/page_navigation', :collection => nav_collection, :as => :page

- unless basket.line_items.count.zero?
	%li
		- clss = 'current' if controller.controller_name == 'baskets'
		= link_to 'Basket', basket_path(basket), :class => clss
		

- if admin_signed_in?
	%li
		=link_to '[Pages]', pages_path
/
	%li.search
		= form_tag search_items_path, :method => 'post' do
			= text_field_tag :search, params[:search]

app/views/layouts/_page_navigation.html.haml
-# clss = ''
- unless page.published == false
	%li
		- unless page.links_to?
			- clss = 'current' if request.path == "/pages/#{page.permalink}"
			= link_to h(page.name), { :controller => '/pages', :action => 'show', :id => page.permalink }, :class => clss
		- else
			- clss = 'current' if request.path == page.links_to
			= link_to h(page.name), page.links_to, :class => clss

		- unless page.children.empty?
			%ul
				= render :partial => 'layouts/menubar', :collection => page.children, :as => :page

app/views/layouts/_sidebar.html.haml
- if content_for? :sidebar
	= yield :sidebar

- unless controller.controller_name == 'baskets'
	= render 'layouts/basket', :basket => current_basket
- else
	%h1
		Help
	%p
		Aliquam erat volutpat. Mauris vel neque sit amet nunc gravida congue sed sit amet purus.
	%p
		Vestibulum mollis mauris enim. Morbi euismod magna ac lorem rutrum elementum. Donec viverra auctor lobortis.

	%img{:src => '/images/paypal.gif', :alt => 'This site uses PayPal.'}

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:charset => 'utf-8'}
	
		%title
			=content_for?(:title) ? yield(:title) + ' | ' : ''
			=t :store_name, :scope => 'views.application'

		= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
		/[if IE]
			= stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
		
		= csrf_meta_tag
		
		= javascript_include_tag 'modernizr'
	%body
		.wrap
		
			%header
				.ninesixty
					%h1
						%a{:href => root_path, :title => 'Home'}
							=t :store_name, :scope => 'views.application'
		
					%nav
						%ul
							= render 'shared/navigation', :basket => current_basket

			.content.ninesixty
	
				.grid_9
					.main
	
						- flash.each do |key, msg|
							%div{:id => key}
								= msg
						
						-# javascript page classification, see application helper
						%span{:id => 'classifier', :class => classifier_class}
						
						= yield
				
				%div.sidebar.grid_3
					= render 'shared/sidebar'
		
			.push
		
		%footer
			.ninesixty
				%span
					=t :store_owner, :scope => 'views.application'
					&copy;
					= Time.now.year
				%span.right
					- if admin_signed_in?
						= link_to 'Logout', destroy_admin_session_path
					- else
						= link_to 'Login',  new_admin_session_path
		
		= javascript_include_tag 'jquery', 'rails', 'jquery.color', 'lightbox', 'application'